-- Title: SQL Practice Exercises
-- Made by Valerie Lim
-- Date: 28 July 

-- Qn1
SELECT *
FROM EMPLOYEES;

-- Qn2
SELECT DISTINCT MANAGER_ID
FROM EMPLOYEES;

--Qn3
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY, 
		(SALARY*1.2) AS ANNUAL_SAL
FROM EMPLOYEES;

--Qn4
SELECT * 
FROM EMPLOYEES
WHERE HIRE_DATE < (1992-01-01); -- Assume YYYY-MM-DD format

--Qn5
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_ID,
FROM EMPLOYEES
WHERE DEPARTMENT_ID != (20, 60, 80);

--Qn6
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e'; -- Assume data stored in small letters

--Qn7
SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE ('%l%', '%j%', '%k%', '%L%', '%J', '%K%')
ORDER BY SALARY DESC;

--Qn8
SELECT *
FROM EMPLOYEES
WHERE (SALARY >= 6000 AND SALARY <= 80000 AND COMMISSION_PCT IS NOT NULL) 
	OR (DEPARTMENT_ID =! (80, 90, 100) AND HIRE_DATE > (1990-01-01));

--Qn9
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN (1990-12-12) AND (1998-04-17); 
-- Assume hiredate only stores DATE info, no TIME info

--Qn10
SELECT FIRST_NAME||''||LAST_NAME AS FULL_NAME, -- CONCAT
		HIRE_DATE, COMMISSION_PCT, PHONE_NUMBER, SALARY
FROM EMPLOYEES
WHERE SALARY > 10000 OR PHONE_NUMBER LIKE '__5%' -- NUMB
ORDER BY FIRST_NAME DESC;

--Qn11
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50, 80);

SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 OR DEPARTMENT_ID = 80;



